# Generated by Django 6.0.5 on 2026-05-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_document_delete_orderdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertimeline',
            name='file',
        ),
        migrations.RemoveField(
            model_name='ordertimeline',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='ordertimeline',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
